config/routes.rb
R20130214Cookbook::Application.routes.draw do
  resources :books, :recipes, :ingredients
end

app/models/book.rb
# == Schema Information
#
# Table name: books
#
#  id      :integer          not null, primary key
#  title   :string(255)
#  chef    :string(255)
#  cuisine :string(255)
#  image   :text
#  isbn    :text
#

class Book < ActiveRecord::Base
  attr_accessible :title, :chef, :cuisine, :image, :isbn, :recipe_ids
  has_many :recipes
end

app/models/ingredient.rb
# == Schema Information
#
# Table name: ingredients
#
#  id          :integer          not null, primary key
#  name        :string(255)
#  measurement :string(255)
#  cost        :decimal(, )
#  image       :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Ingredient < ActiveRecord::Base
  attr_accessible :name, :measurement, :cost, :image
  has_and_belongs_to_many :recipes
end

app/models/recipe.rb
# == Schema Information
#
# Table name: recipes
#
#  id           :integer          not null, primary key
#  name         :string(255)
#  course       :string(255)
#  cooktime     :string(255)
#  servingsize  :integer
#  instructions :text
#  image        :text
#  book_id      :integer
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

class Recipe < ActiveRecord::Base
  attr_accessible :name, :course, :cooktime, :servingsize, :instructions, :image, :book_id, :ingredient_ids
  belongs_to :book
  has_and_belongs_to_many :ingredients
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = Book.all
  end
  def create
    book = Book.create(params[:book])
    redirect_to(book)
  end
  def new
    @book = Book.new
  end
  def show
    @book = Book.find(params[:id])
  end
  def edit
    @book = Book.find(params[:id])
  end
  def update
    book = Book.find(params[:id])
    book.update_attributes(params[:book])
    redirect_to(book)
  end
  def destroy
    book = Book.find(params[:id])
    book.delete
    redirect_to(books_path)
  end
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  def index
    @ingredients = Ingredient.all
  end
  def create
    ingredient = Ingredient.create(params[:ingredient])
    redirect_to(ingredient)
  end
  def new
    @ingredient = Ingredient.new
  end
  def show
    @ingredient = Ingredient.find(params[:id])
  end
  def edit
    @ingredient = Ingredient.find(params[:id])
  end
  def update
    ingredient = Ingredient.find(params[:id])
    ingredient.update_attributes(params[:ingredient])
  end
  def destroy
    ingredient = Ingredient.find(params[:id])
    ingredient.delete
    redirect_to(ingredients_path)
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def index
    @recipes = Recipe.all
  end
  def create
    recipe = Recipe.create(params[:recipe])
    redirect_to(recipe)
  end
  def new
    @recipe = Recipe.new
  end
  def show
    @recipe = Recipe.find(params[:id])
  end
  def edit
    @recipe = Recipe.find(params[:id])
  end
  def update
    recipe = Recipe.find(params[:id])
    recipe.update_attributes(params[:recipe])
    redirect_to(recipe)
  end
  def destroy
    recipe = Recipe.find(params[:id])
    recipe.delete
    redirect_to(recipes_path)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/books/edit.html.erb
<div id='bookbox'>
<h1>Edit Book:</h1>
<br>
<%= form_for @book do |f| %>

  <%= f.label :title %>
  <%= f.text_field :title %>
  <br>
  <br>
  <%= f.label :chef %>
  <%= f.text_field :chef %>
  <br>
  <br>
  <%= f.label :cuisine %>
  <%= f.text_field :cuisine %>
  <br>
  <br>
  <%= f.label :isbn %>
  <%= f.text_field :isbn %>
  <br>
  <br>
  <%= f.label :image %>
  <%= f.text_field :image %>
  <br>
  <br>
  <%= f.submit %>
<% end %>
</div>

app/views/books/index.html.erb
<ol>
  <li>
    <% @books.each do |book| %>
      <div id='bookbox'>
        <h1><%= link_to book.title, book %></h1>
        <p><%= book.chef %></p>
        <p><%= book.cuisine %></p>
        <%= image_tag(book.image) %>
      </div>
    <% end %>
  </li>
</ol>

app/views/books/new.html.erb
<div id='bookbox'>
<h1>Add Book:</h1>
<br>
<%= form_for @book do |f| %>

  <%= f.label :title %>
  <%= f.text_field :title %>
  <br>
  <br>
  <%= f.label :chef %>
  <%= f.text_field :chef %>
  <br>
  <br>
  <%= f.label :cuisine %>
  <%= f.text_field :cuisine %>
  <br>
  <br>
  <%= f.label :isbn %>
  <%= f.text_field :isbn %>
  <br>
  <br>
  <%= f.label :image %>
  <%= f.text_field :image %>
  <br>
  <br>
  <% Recipe.order(:name).all.each do |recipe| %>
    <%= check_box_tag 'book[recipe_ids][]', recipe.id, recipe.in?(@book.recipes.to_a) %>
    <span><%= recipe.name %></span>

    <br>
  <% end %>

  <br>
  <%= f.submit %>
<% end %>
</div>

app/views/books/show.html.erb
<nav class='single_menu'><%= link_to '+ Add New Book', new_book_path %></nav>

<div id='bookbox'>
  <h1><%= link_to @book.title, @book %></h1>
  <p><%= @book.chef %></p>
  <p><%= @book.cuisine %></p>
  <%= image_tag(@book.image) %>
  <br>
  <p><%= link_to 'delete', @book, :method => :delete, :confirm => 'Are you sure?' %></p>
  <p><%= link_to 'edit', edit_book_path(@book) %>



</div>

<br>

<% @book.recipes.each do |recipe| %>

<div id='bookbox'>
  <h1>Featured Recipe</h1>
  <p><%= recipe.name %></p>
  <%= image_tag(recipe.image) %>

  <br>
</div>
<div id='ingredientbox'>
  <h1>Main Ingredients</h1>
  <% recipe.ingredients.each do |ingredient| %>
    <div class='ing_img'>
    <%= image_tag(ingredient.image) %>
    </div>
    <p><%= ingredient.name %></p>

  <% end %>
</div>


<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>R20130214Cookbook</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

  <nav>
    <ul>
      <li><%= link_to 'Books', books_path %></li>
      <li><%= link_to 'Recipes', recipes_path %></li>
      <li><%= link_to 'Ingredients', ingredients_path %></li>
    </ul>
  </nav>

<%= yield %>

</body>
</html>

app/views/recipes/index.html.erb
<ol>
  <li>
    <% @recipes.each do |recipe| %>
      <div id='bookbox'>
        <%= image_tag(recipe.image) %>
        <h1><%= link_to recipe.name, recipe %></h1>
        <p><%= recipe.name %></p>
        <p><%= recipe.course %></p>
        <p><%= recipe.cooktime %></p>
        <p><%= recipe.servingsize %></p>
        <p><%= recipe.instructions %></p>
      </div>
    <% end %>
  </li>
</ol>

app/views/recipes/new.html.erb
<div id='bookbox'>
<h1>Add Recipe:</h1>
<br>
<%= form_for @recipe do |f| %>

  <%= f.label :name %>
  <%= f.text_field :name %>
  <br>
  <br>
  <%= f.label :course %>
  <%= f.text_field :course %>
  <br>
  <br>
  <%= f.label :cooktime %>
  <%= f.text_field :cooktime %>
  <br>
  <br>
  <%= f.label :servingsize %>
  <%= f.text_field :servingsize %>
  <br>
  <br>
  <%= f.label :instructions %>
  <%= f.text_field :instructions %>
  <br>
  <br>
  <%= f.label :image %>
  <%= f.text_field :image %>
  <br>
  <br>
  <% Ingredient.order(:name).all.each do |ingredient| %>
    <%= check_box_tag 'recipe[ingredient_ids][]', ingredient.id, ingredient.in?(@recipe.ingredients.to_a) %>
    <span><%= ingredient.name %></span>

    <br>
  <% end %>
  <br>
  <%= f.submit %>
<% end %>
</div>

app/views/recipes/show.html.erb
<nav class='single_menu'><%= link_to '+ Add New Recipe', new_recipe_path %></nav>

<div id='bookbox'>
  <%= image_tag(@recipe.image) %>
  <h1><%= link_to @recipe.name, @recipe %></h1>
  <p><%= @recipe.course %></p>
  <p><%= @recipe.cooktime %></p>
  <p><%= @recipe.servingsize %></p>
  <p><%= @recipe.instructions %></p>
  <p><%= link_to 'delete', @recipe, :method => :delete, :confirm => 'Are you sure?' %></p>
  <p><%= link_to 'edit', edit_book_path(@recipe) %>
</div>
</div>
<div id='ingredientbox'>
  <h1>Main Ingredients</h1>
  <% @recipe.ingredients.each do |ingredient| %>
    <div class='ing_img'>
    <%= image_tag(ingredient.image) %>
    </div>
    <p><%= ingredient.name %></p>

  <% end %>
</div>